//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTkStudy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenTkStudy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 460
        ///
        ///out vec4 pixelColor;
        ///
        ///void main()
        ///{
        ///    pixelColor = vec4(0.8f, 0.8f, 0.1f, 1.0f);
        ///}
        ///.
        /// </summary>
        internal static string PixelShader {
            get {
                return ResourceManager.GetString("PixelShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 460
        ///
        ///out vec4 pixelColor;
        ///
        ///void main()
        ///{
        ///    pixelColor = vec4(0.8f, 0.8f, 0.1f, 1.0f);
        ///}
        ///.
        /// </summary>
        internal static string PixelShader2 {
            get {
                return ResourceManager.GetString("PixelShader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PixelShaderFt {
            get {
                return ResourceManager.GetString("PixelShaderFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shader_test {
            get {
                object obj = ResourceManager.GetObject("shader_test", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* This animation is the material of my first youtube tutorial about creative
        ///   coding, which is a video in which I try to introduce programmers to GLSL
        ///   and to the wonderful world of shaders, while also trying to share my recent
        ///   passion for this community.
        ///                                       Video URL: https://youtu.be/f4s1h2YETNY
        ///*/
        ///uniform float iTime;
        ///uniform vec2 iResolution;
        ///
        /////https://iquilezles.org/articles/palettes/
        ///vec3 palette(float t) {
        ///    vec3 a = vec3(0.5, 0.5, 0.5);
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test2_glsl {
            get {
                return ResourceManager.GetString("test2.glsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 460
        ///
        ///layout (location = 0) in vec3 aPosition;
        ///
        ///void main()
        ///{
        ///    gl_Position = vec4(aPosition, 1.0f);
        ///}
        ///.
        /// </summary>
        internal static string VertexShader {
            get {
                return ResourceManager.GetString("VertexShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 460
        ///
        ///layout (location = 0) in vec3 aPosition;
        ///
        ///void main()
        ///{
        ///    gl_Position = vec4(aPosition, 1.0f);
        ///}
        ///.
        /// </summary>
        internal static string VertexShader2 {
            get {
                return ResourceManager.GetString("VertexShader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VertexShaderFt {
            get {
                return ResourceManager.GetString("VertexShaderFt", resourceCulture);
            }
        }
    }
}
